#valable (ตัวแปล)
stu_id = input('Student        ID  : ')
stu_name = input('Student       Name : ')
stu_by = input('Student Birth Year : ')
print ('---------------------------------------')
print (f'ยินดีต้อนรับ {stu_id} {stu_name} สู่ SAU')
print (f'คุณเกิดปี {stu_by} แปลว่าคุณอายุ {2023 - int(stu_by)} ปี') #int({stu_by})
print ('ใช้ ,  ---------------------------------------')
print ('ยินดีต้อนรับ' ,(stu_id), (stu_name), 'สู่ SAU')
print ('คุณเกิดปี' ,stu_by, 'แปลว่าคุณอายุ' ,2023 - int(stu_by), 'ปี')
print ('ใช้ +  ---------------------------------------')
print ('ยินดีต้อนรับ'+stu_id+'  '+stu_name+'สู่ SAU' )
print ('คุณเกิดปี' +stu_by+" แปลว่าคุณอายุ "+str(2023 - int(stu_by))+ 'ปี')
print ('ใช้ เมธอด format ---------------------------------------')
print ('ยินต้อนรับ {} {} สู่ SAU' .format(stu_id,stu_name))
print ('คุณเกิดปี {} แปลว่าคุณอายุ {} ปี'.format(stu_by , 2023 - int(stu_by)))